---
all:
  hosts:
    # Add your LAN machines here:
    # server1:
    #   ansible_host: 192.168.1.10
    # server2:
    #   ansible_host: 192.168.1.11
    localhost:
      ansible_connection: local
  vars:
    ansible_user: sandrasko
    dotfiles_repo: /vault/dotfiles
